name: Build

on:
  push:

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    environment: release
    steps:
    - name: Validate
      uses: quintenroets/package-dev-tools/actions/validate@main

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: release
    permissions:
      id-token: write  # Needed for PyPi publishing
      contents: write  # Needed for GitHub publishing
    steps:
      - name: Publish
        uses: quintenroets/package-dev-tools/actions/publish@main
