name: Publish package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - name: Publish
        uses: quintenroets/workflows/publish@main
