name: Publish package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      id-token: write  # Needed for PyPi publishing
      contents: write  # Needed for GitHub publishing
    steps:
      - name: Publish
        uses: quintenroets/actions/publish@main
