name: Publish package

on:
  push:

jobs:
  run-pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Run pre-commit
        uses: quintenroets/workflows/run-pre-commit.yml@main
